# Chat configuration
[chat]
# Maximum number of conversation pairs (user + assistant) to include in context
max_conversation_pairs = 50

# OpenAI configuration
[openai]
temperature = 0.7
model = "gpt-4"  # This will be overridden by AZURE_OPENAI_DEPLOYMENT_NAME if set

# Logging configuration
[logging]
level = "info"
